### ISSUE TITLE
org.jetbrains.intellij:blockmap:1.0.5 was re-released with a different pom

### ISSUE THREAD

**Issue by stefansaasen** [JetBrains/plugin-blockmap-patches#1]
I'm using the `gradle-intellij-plugin` plugin version 0.7.2 and I have dependency locking enabled in my Gradle build scripts.

Today my build started to fail with the following message:

```
A problem occurred configuring project ':plugin'.
> Could not resolve all artifacts for configuration ':plugin:classpath'.
    > Resolved 'software.amazon.awssdk:bom:2.11.9' which is not part of the dependency lock state
```

This seemed odd as no dependency or build script changes happened.

After some investigation, it looks like `org.jetbrains.intellij:blockmap:1.0.5` was re-released with a different pom, now importing the `software.amazon.awssdk:bom`.

Release date of `org.jetbrains.intellij:blockmap:1.0.5` is the 13th of April, even though the version `1.0.5` was used as a dependency in the `gradle-intellij-plugin:0.7.2`, which was released a while ago:

![Screenshot 2021-04-14 at 16 42 14](https://user-images.githubusercontent.com/77052806/114732794-1bd14000-9d43-11eb-9381-04681552794c.png)

There's a different `pom.xml` for version `1.0.5` that does *not* import the `awssdk` bom: https://jcenter.bintray.com/org/jetbrains/intellij/blockmap/1.0.5/blockmap-1.0.5.pom - so 1.0.5 now exists in two different flavours...

Expected:

* Artefacts don't change

Actual results:

* The artefact (at least the `pom.xml`) changed but was released using a previously used version number (`1.0.5`).

**Comment by TarCV** [comment]
Got a similar issue too. Recently JAR and POM for 1.0.5 were replaced in Gradle Plugin Repository breaking locked builds for me when caches expired. I don't see anything malicious with diffoscope though, it is just recompiled with different Kotlin version (1.4 instead of 1.3) and has changed dependencies as described above.

**Comment by chrkv** [comment]
Hi! This was a one-time issue with publishing to Maven Central. Unfortunately we can't update the version uploaded to Maven Central, but this would not happen in the future.
